### ISSUE TITLE
ReadMe typo in installation

### ISSUE THREAD

**Issue by Ofghanirre** [cisstech/platon#1]
Hello ! Dans le README, sur l'initialisation de la database, il y a une typo dans la commande à exécuter:
`./bin/migrations/run.sh`, le dossier `migrations` n'existe pas, il s'appelle `migration` de ce que je peux voir ! 

ça vaudrait le coup de modifier ça ! :)

Sinon je me demandais si il serait possible de concaténer des opérations en une seule commande:

Exemple:

---

> ./bin/migrations/run.sh
> ./bin/init-db.sh 

> Mettre (si possible) le run.sh dans le init-db

---

> yarn graphql:generate
> yarn serve:web 

> Mettre (si possible) la generation de graphql directement en tâche préfixant le serve:web

Je ne m'y connais pas trop en script donc je me demande si c'est possible :)

La bonne journée et merci pour ce travail formidable !

**Comment by mciissee** [comment]
Merci pour les typo  @Ofghanirre c'est fix, pour le fait de concaténer les scripts il y a une raison qui fait que c'est des commandes séparés.

- ./bin/init-db doit être lancée qu'une seule fois durant le développement c'est à l'installation pour créer les données de base.
- ./bin/migration/run/sh doit être lancé une fois à l'installation et à chaque fois qu'une nouvelle migration est créé dans le dossier migrations.
- yarn graphql:generate doit être exécuté uniquement à la suite de la création/modification d'un fichier .graphql.ts dans une des lib `browser`
