### ISSUE TITLE
WebComponent options settings

### ISSUE THREAD

**Issue by Ofghanirre** [cisstech/platon#10]
Hello j'ai observé quelques comportements étranges lors de l'utilisation de la plateforme PLaton, notamment aux niveaux de l'écriture d'options et de fields dans l'éditeur:

Si un champs par défaut définis sur une valeur X est définis dans le fichier `.ple`, il semblerait qu'il soit mal initialisé:
![image](https://github.com/cisstech/platon/assets/18609818/08d39d17-ae41-4f03-9579-bf5f110203d9)
_Ici, on initialise l'options debug du composant feedback à true, de telle sorte à ce que le json du composant soit affiché_

Si maintenant on définis le champs `input.debug = false`, on obtient l'affichage suivant:
![image](https://github.com/cisstech/platon/assets/18609818/7d12f8e7-27a9-406e-80b4-b9f071f1f452)

_L'option debug semble avoir été évaluée comme true_
Dis moi si besoin de plus de détails

**Comment by mciissee** [comment]
Fix with https://github.com/cisstech/platon/commit/58f094442bc2919a753c841674bfabc8ae85c5cd
