### ISSUE TITLE
Strange behavior of plf  

### ISSUE THREAD

**Issue by nimdanor** [cisstech/platon#100]
When editing the haha.plf i see the content of main.plf.

https://platon.univ-eiffel.fr/editor/b06f27f9-d899-4960-8136-0bbcd2d01539?version=latest

The haha.plf is empty by when i edit it i get the content of main.plf 
Then when i try to visualize the exercice : 
error 500 
(unknown path) [Line 21, Column 65]
  unexpected token: <

![image](https://github.com/cisstech/platon/assets/10084549/04921303-f940-4355-9f87-1af3dab9985e)

![image](https://github.com/cisstech/platon/assets/10084549/18182696-9478-4a01-9f9a-701b2a83a443)

**Comment by nimdanor** [comment]
j'ai voulu exporter les fichiers mais le fichier main.plf est vide.

**Comment by mciissee** [comment]
I was not able to reproduce the bug it may be caused by a cash problem
