### ISSUE TITLE
@copycontent file.plf doesn't work as advertised

### ISSUE THREAD

**Issue by nimdanor** [cisstech/platon#102]
![image](https://github.com/cisstech/platon/assets/10084549/b56f6886-4fae-4253-a9d1-cebf7720e750)

![image](https://github.com/cisstech/platon/assets/10084549/44492937-bd38-47ba-8b3b-1bc04bf74f82)

No title 
![image](https://github.com/cisstech/platon/assets/10084549/608ef58b-00c2-4712-a49f-bbf12b24d920)

[platon(3).zip](https://github.com/cisstech/platon/files/15378975/platon.3.zip)

**Comment by mciissee** [comment]
There is effectively a bug where title is not rendered as markdown. It's now fixed.
For the fact that you have wrong title in your case and not the one of the plf it seems to be because of the override inside the main.plc that is always predominant so it's not really a bug.

**Comment by nimdanor** [comment]
Top
