### ISSUE TITLE
Preview Refresh

### ISSUE THREAD

**Issue by nimdanor** [cisstech/platon#2]
When using preview in the editor on a activity/exercice. 
If I modify the exercice code i must close and reopen the preview is it possible to do one of two things : 
1) add a refresh action on the name of the preview (or an icon refresh) 
2) an automatique refresh when the exercice is saved

**Comment by nimdanor** [comment]
Ok le bouton preview ré-apparait quand on sauve le fichier source et donc on peut rafraichir sans fermer ! Excellent.

**Comment by nimdanor** [comment]
Re-openning the preview button does not refresh/restart the preview with the new values.

**Comment by mciissee** [comment]
The preview will always take the saved value not on the server not the local value of the editor, so you must save the editor content before previewing
