### ISSUE TITLE
Editor Killer

### ISSUE THREAD

**Issue by nimdanor** [cisstech/platon#21]
super_ton_mega_indentifiant_de_variable = 12

Il doit y avoir un algo super exponentiel quelque part  ...

c'est quoi le code qui gère les "_" dans l'éditeur  ...

En plus on dirait que c'est la thread d'affichage qui gère ...

**Comment by mciissee** [comment]
Je n'arrive pas à reproduire le problème donc je close la PR pour le moment

**Comment by nimdanor** [comment]
Essaye sur platon-preprod.univ-eiffel.fr 
c'est peut être un problème de puissance (pourtant on a rajouté de la mémoire).
