### ISSUE TITLE
Preview Errors

### ISSUE THREAD

**Issue by nimdanor** [cisstech/platon#3]
When doing exercice edition we need a debug view where errors in the code are displayed.

the debug view should below the preview (or take the place of the view in casd of parsing error ) .

the debug view must give us the localisation of the problem:

1) while parsing the 'ple' / 'plf' 'p*' ?
2) while exécuting the "build" or the "grade" in javascript sandbox 
3) while exécuting the "build" or the "grade" in the full sandbox 
4) while another "step" in the process.

If the globals of the build/grade python executable could be in the debug view.

**Comment by mciissee** [comment]
The exercise player will not display compilation errors : 
<img width="1364" alt="Capture d’écran 2023-06-03 à 23 19 15" src="https://github.com/cisstech/platon/assets/30326262/2e29fd2b-509e-4101-85b3-ea5375f49719">

**Comment by nimdanor** [comment]
Ok pas vu merci 
notre préprod n'est pas a jour ;)
