### ISSUE TITLE
Can't grade exercice

### ISSUE THREAD

**Issue by nimdanor** [cisstech/platon#36]
On platon-preprod 

trying exercice : "C'est quoi une variable" 

when asking to be evaluated go this for an answer :

Execution of the evaluating script failed due to an an unknown error. Please contact your teacher :

already piping an entry

**Comment by mciissee** [comment]
It looks like your exercise has an error with a python sandbox. As already seen with @NewMeeh  and @Ofghanirre , this error and all errors related to python sandbox execution are outside the scope of this repository

**Comment by nimdanor** [comment]
The problem is related to the fabrication in javascript of the tarball 
https://github.com/mafintosh/tar-stream/issues/24

**Comment by nimdanor** [comment]
The problem is if no variable builder or grader is define 
the script.py is undefined and it make the tar library to fail
