### ISSUE TITLE
Probleme d'affichage de certains webComponents

### ISSUE THREAD

**Issue by Ofghanirre** [cisstech/platon#37]
Salut j'espère que tu vas bien!
On se retrouve face à des problèmes d'affichages de certains WebComponents.

Sont concernés:
> - CheckBoxGroup
> - SortList
> - Autres???

Output console :
> Pas d'erreurs, un warning en local, pas sur le serveur preprod: 
>   >`Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming`

Sur l'inspecteur je remarque que le contenu des webcomponents semblent correcte, il y a le composant joué et la solution... Mais non chargées...

<img width="1466" alt="Capture d’écran 2023-08-28 à 10 20 10" src="https://github.com/cisstech/platon/assets/18609818/699ac1bd-379b-4ded-ac3e-068916febd12">

Et on obtient l'affichage suivant:
<img width="669" alt="image" src="https://github.com/cisstech/platon/assets/18609818/6765034b-c203-43e8-a3b4-d82b69cc143c">

Pistes possibles:
- Plus tôt j'avais ajouté 3 webComposants permettant à un utilisateur d'afficher des graphes : pie, bar et radar
> Ils marchaient pendant un temps, mais j'avais des erreurs d3, et depuis dans la documentation seul le radar s'affiche correctement.
> Je ne sais pas si c'est lié avec les autres composants, si d3 est impliqué ou quoi, peux être sauras-tu m'éclairer. J'ai tenté de mettre ta version, une version plus récente, rien n'y fait.

- J'ai normalement check le côté API, rien n'a changé, donc je ne pense pas que ça soit cela...

Point étranges:
- Les composants checkboxGroup & SortList fonctionnent dans la documentation Platon

Lien rapide vers la doc d'un composant:
https://platon-preprod.univ-eiffel.fr/docs/pages/widgets/wc-chart-viewer-radar

Voilà j'espère avoir bien décris le problème :/
Si tu as besoin de quoi que ce soit fais le moi savoir!

En attendant je te souhaite une bonne journée

**Comment by Ofghanirre** [comment]
Fichier utiliser pour faire un exercice CheckBoxGroup:
```py
sandbox="python"

checkBox = :wc-checkbox-group

cBSolution = :wc-checkbox-group
cBSolution.disabled = true

good == 
réponse1
réponse2
==

bad ==
réponse3
réponse4
réponse5
réponse6
==

/* total de réponses disponibles pour le user*/
amountBad = 2
amountGood= 2

horizontal = False

builder==#!lang=python
checkBox["disabled"] = False

from random import shuffle, sample

good_list = good.split("\n")


result = sample(good_list, amountGood)
result += sample(bad.split("\n"), amountBad)
shuffle(result)

checkBox["items"] = [{"content": choix} for choix in result]
cBSolution["items"] = [{
  "content": choix, 
  "checked": choix in good_list, 
  "css": "border-color: green;" if choix in good_list else "border-color: red; opacity: 0.5;"
} for choix in result]

if horizontal:
  checkBox["horizontal"] = True
  cBSolution["horizontal"] = True
==

grader==#!lang=python
grade = 0
feedback["type"] = "error"
feedback["content"] = "Mauvaise réponse"


list1 = list(map(lambda el: bool(el.get("checked")), checkBox["items"]))
list2 = list(map(lambda el: bool(el.get("checked")), cBSolution["items"]))

if list1 == list2:
  grade = 100
  feedback["type"] = "success"
  feedback["content"] = "Bonne réponse"

#checkBox = cBSolution
for i in range(len(checkBox["items"])):
  checkBox["items"][i]["css"] = cBSolution["items"][i]["css"]
checkBox["disabled"] = True
==


title==
Addition aléatoire
==

statement ==
Pitié marche
==

form==
{{checkBox}}
==

solution==
{{cBSolution}}
==

```

Note:
> Je me demande si c'est pas lié au ngemarkdown, vu qu'il y a eu une maj. et que les composants sont affichés dans une balise ngemarkdown...
> On creuse avec thomas en même temps
> J'ai essayé depuis ta branche main, et même problème :/

**Comment by mciissee** [comment]
Salut @Ofghanirre, le problème est désormais fix sur master, c'était dû à un non appel du détecteur de changement d'angular lorsque l'état d'un composant changeait dans certains cas.

<img width="1512" alt="Capture d’écran 2023-08-28 à 12 13 35" src="https://github.com/cisstech/platon/assets/30326262/4adadba9-73a6-4d48-b87a-2dd33980bcb6">

Par ailleurs, si vous faites un merge de master, vos 3 composants qui utilisent la lib ngx-charts ne fonctionneront pas car j'ai update d3 à sa dernière version (7), Il y avait une différence de 3 à 4 versions majeurs avec la version de ngx-charts. Pour cette raison j'ai retiré la lib ngx-charts du projet pour la remplacer par [echarts](https://echarts.apache.org/en/index.html) qui est plus stable, a une meilleure maintenance et contient de meilleurs composants.

<img width="1273" alt="Capture d’écran 2023-08-28 à 11 34 34" src="https://github.com/cisstech/platon/assets/30326262/0c51aa05-771b-45ff-90de-5e2b8cbc7a99">

**Comment by Ofghanirre** [comment]
ça marche merci beaucoup pour les explications, j'ai regardé echarts, mise à part leur site ça a l'air très pratique
