### ISSUE TITLE
IU changement pratique : Edition / affichage de ressources

### ISSUE THREAD

**Issue by Ofghanirre** [cisstech/platon#6]
Hello ! J'aimerai proposer un changement pour une utilisation dans l'affichage / edition  de ressource sur Platon:
![Capture d’écran 2023-06-05 135407](https://github.com/cisstech/platon/assets/18609818/5207f301-035c-4cf7-97ed-95ce5e17d9b6)

Serait-il possible de faire en sorte qu'on accède à l'édition d'un fichier en double cliquant sur ce même fichier directement depuis l'interface ci-dessus.
> Exemple:
> _On double clique sur main.ple et on accède à cet interface ;_
![Capture d’écran 2023-06-05 135855](https://github.com/cisstech/platon/assets/18609818/14e71ea0-cc0b-4ad8-81d6-270ea53da2d1)

C'est purement pour un côté ergonomie, et après l'avoir utilisé / présenté à quelques utilisateurs, j'ai remarqué que tout le monde avait tendance à double cliquer pour éditer, donc je pense que ce comportement pourrait être pertinent à implémenter!

Je te souhaite une bonne journée!

**Comment by mciissee** [comment]
La solution est implémentée avec ce commit : https://github.com/cisstech/platon/commit/5af4df89461cc2ee7a7aa76b74ec5898634e71d2

Il te manquait sans doute un `await` sur l'appel à la méthode `fileService.registerFolders` pour attendre d'enregistrer les fichiers sinon l'éditeur ne trouveras pas les fichiers que tu veux ouvrir.
