### ISSUE TITLE
[Small fix] link to component documentation from exercice editor

### ISSUE THREAD

**Issue by nborie** [cisstech/platon#64]
The link to the components documentation (`wc-input-box` for example) seems broken.

Since the good documentation already exists, just fix the link to the good page. The buttom to click to get the documentation is at left and at tle bottom of the editor page ont the doc icon (the small book).

![Capture d’écran du 2024-01-23 14-33-29](https://github.com/cisstech/platon/assets/6042616/246d7f4f-be67-48ae-954f-01bd22bb336b)

Both links to editor documenation and programmation guid documentation work well.

**Comment by mciissee** [comment]
https://github.com/cisstech/platon/assets/30326262/d36381ee-1b14-4eea-82f4-66d74a92a572

The functionality seems to work locally with the main repository and on platon-preprod. From what I can see on your screen with the content of the "TODO" documentation, it could be that there's a cache problem on your browser, as the content of the `presentation.md` file is no longer the same.  https://github.com/cisstech/platon/blob/main/libs/feature/webcomponent/src/lib/docs/presentation.md

I suggest you clear your browser's cache and try again.
