### ISSUE TITLE
Copy of reference to component in python builder/grader

### ISSUE THREAD

**Issue by nborie** [cisstech/platon#70]
Here is a strange minimal code
```
sandbox="python"

title="Une copy de référence est faite dans le builder avant présentation"

CG=:wc-checkbox-group

builder==#!lang=python
CG['items'] = [{"content" : "Coche Moi !"}, {"content" : "Coche Moi aussi !"}]
COPY = CG
==

statement==
Il faut cocher ou pas puis évaluer....
==


form==
{{ COPY }}
==

grader==#!lang=python
feedback['content'] = "La copie : " + str(COPY) 
feedback['content'] += "<br /><br />L'original :" + str(CG) 
==
```
When evaluating (grader) the answer, sometimes, the keys `checked` are not present in the items of the checkbox-group component. Idéally, original ref and copied ref should all get the keys `checked` setted to True or False. The behaviour is not the same if one put `{{ CG }}` or `{{ COPY }}` in the `form`.

**Comment by mciissee** [comment]
@nborie @NewMeeh  C'est fix désormais.

En complément du fix, si vous souhaitez instancier un component depuis le builder/grader, la fonction `component(selector: string)` est disponible sur les 2 types de sandbox. Elle n'est pas encore sur la doc, mais la feature est déjà présente sur l'application.
