### ISSUE TITLE
Course dashboard for Courses in `challenge` mode

### ISSUE THREAD

**Issue by nborie** [cisstech/platon#78]
[THERE IS A CHOICE TO MAKE! : THIS QUESTION IS VERY IMPORTANT OR TO BE CARRIED OUT VERY LATEST...]

This involves organizing a programming challenge on the PLaTon platform.

Currently we have 7 secret free language choice algorithmic problems. If we want to organize a competition on PLATon, we need a dashboard adapted to the competition. We would therefore like a reusable dashboard for all `challenge` type courses.

A `challenge` type course is an open course (linked to a free registration moodle in student mode only). The `challenge` mode means that learners are publicly classified in this type of course (when you agree to participate, that's how...). All teachers of this activity are organizers and do not have the right to participate in the competition.

We would therefore like a public dashboard for teachers and students based on the Avdent of Code (AOC) model. Ideally, you need one dashboard for the course and one dashboard per challenge. The dashboard for the entire `challenge` course might look like this:
We see sorted for the participants with the sum of their points on ALL the challenges (i.e. all the activities in the course).

![Capture d’écran du 2024-02-05 12-50-14](https://github.com/cisstech/platon/assets/6042616/26f557a1-e033-4f17-9c00-09cfadd410e2)

We want to organize the competition over a week (7 days). Basically, we would also need a dashboard for each of the challenge activities in this challenge course. Here is the template for a single challenge in Advent of Code:
The first to solve the problem (we see the time in minutes and seconds) scores 100 points, the second 99, the third 98 and so on.

![Capture d’écran du 2024-02-05 12-50-21](https://github.com/cisstech/platon/assets/6042616/e7ced693-3576-4ebd-b6d2-edff16fb2fd4)

If you are ok to dealt with this issue very shorlty (2 or 3 three weeks max) to deploy, test and organise this competition in less dans 2 mounth now, please comment under this post.

We would like to change the grade : The `challenge` grade under PLaTon should be as it follows :

grade course challenge = sum ( grade activity challenge in the course )

grade activity challenge in the course = PLaTon grade (0-100) of the exercice inside the activity + (0-100) Bonus if you answer correctly in the 100 firsts

**Comment by nborie** [comment]
Une activité de type challenge est une activité comme les autres. La seule chose qui change est son dashboard et sa notation :

Profs (organisateurs du challenge) et Élèves (participants du challenge) voit le même dashboards de cours :

* utilisateurX : +(00:15:45) 200 points
* utilisateurX : +(00:16:21) 199 points
* utilisateurX : +(00:18:02) 198 points
* utilisateurX : +(00:25:34) 197 points
* utilisateurX : +(00:36:54) 196 points
* utilisateurX : +(00:40:41) 195 points
* utilisateurX : +(01:02:12) 194 points
* utilisateurX : +(01:08:45) 193 points
* ...
* utilisateurX : + > 24 heures 100 points
* utilisateurX : + > 24 heures 100 points
* utilisateurX : + > 24 heures 100 points

(On affiche pas les utilisateurs qui ont un score nul...)

![lien_leader_board](https://github.com/cisstech/platon/assets/6042616/7a140168-2db8-403d-98f9-d6ede9773217)

--> Ce tableau des scores d'activités doit pourvoir être consulté par tout le monde (profs et élèves) dans un onglet statistique de l'activité en mode `challenge`. Je vois bien ce leaderborad dans la vue à l'URL `https://platon.univ-eiffel.fr/activities/code-hexa-du-cours/code-héxa-de-l'activité`. En gros ce leaderbord remplace la vue au dessous quand on est en mode challenge.

![activité_challenge](https://github.com/cisstech/platon/assets/6042616/1f3af803-3abd-49ff-a540-daccaf916b72)

Un cours de type challenge est un cours comme les autres. La seule chose qui change est son dashboard et sa notation :

Profs (organisateurs du challenge) et Élèves (participants du challenge) voit le même dashboards de cours :

* utilisateur1 : 764 points
* utilisateur2 : 757 points
* utilisateur3 : 750 points
* utilisateur4 : 750 points
* utilisateur5 : 745 points
* ....
* utilisateur324 : 100 point

(On affiche pas les utilisateurs qui ont un score nul...)


--> Ce tableau de type leaderboard qui est juste une liste ordonné en partant du grand gagnant vers le participant ayant le moins de points peut tout à fait ce placer en bas du dashboard classique des courses (il suffira ainsi de scroller au dessus des activités de type challenge pour le voir). voir screenshot au dessous. (URL du type : `https://platon.univ-eiffel.fr/courses/code-héxa-du-cours/dashboard`).

![courses_leaderboard](https://github.com/cisstech/platon/assets/6042616/2e4b07b3-6c14-4017-8428-72f9fa76ad5e)


Comme les problèmes seront programmée pour être publié tous les jours à 20 heures. Les besoins sont surtout :
* être capable de lister les 100 permiers utilisateurs à résoudre les activités challenge correctement (100 / 100 au grade car il y aura un seul exercice dans chaque challenge)
* faire les vues pour les leaderboards

Je ne sais pas si c'est complètement explicite.... Le but est clairement d'adapter au minimum PLaTon (quitte à affiner plus tard) pour y faire des activité ouvertes en mode concours.

**Comment by mciissee** [comment]
@nborie Pour pour l'explication détaillée, c'est plus clair comme ça.

Je vous propose la chose suivante : 

- Ne pas mettre de notion de cours challenge
- Permettre au moment de la création d'une activité spécifier si c'est un challenge
- Dans le cas où l'activité est un challenge, on ne peut pas choisir de participants ni de correcteur. Dans ce cas les personnes pouvant y répondre sont les élèves du cours.
- Si un cours à au moins une activité de type challenge, on affiche un leaderboard sur la page du cours
- Si une activité est de type challenge, son dashboard est adaptée

Voici globalement ma proposition d'implémentation dites moi s'il y a des points importants que j'ai oublié.

**Comment by mciissee** [comment]
Pour l'aspect programmation de la publication des activités, c'est comme c'est fait actuellement, en choisissant de limiter l'accès à une date dans le formulaire de création et il faut les faire manuellement sur la plateforme
<img width="1297" alt="Capture d’écran 2024-02-05 à 20 27 05" src="https://github.com/cisstech/platon/assets/30326262/8083dcdc-20a8-4b1f-ad2e-0ed0bf25e56f">

**Comment by nborie** [comment]
Here is an kind of minimal example to test challenge activity. The best is to place this alone exercise inside a challenge activity
```
sandbox="python"

ans=:wc-input-box
ans.type="number"


title="Exemple de challenge"

builder==#!lang=python
import random

soluce_num = random.randint(1000000, 9999999)
nb_prop = 0
time_prop = []
==

statement==#!lang=python

Il y a systématiquement un énoncé qui est un gros challenge pour lequel il faut coder pour trouver la solution. L'exercice se termine 
par une donnée unique générée par le `builder`. En fait, quand l'exercice n'est pas trivial, le `builder` génère aussi la 
solution personnalisée du challenge qui sera toujours un gros entier (comme dans le projet Euler ou encore l'advent of code).

Votre donnée personalisée qui est aussi la solution à ce challenge trivial est ici au dessous :
<pre>
{{ soluce_num }}
</pre>
==

form==

{{ ans }}

==


grader==#!lang=python
import datetime
import time

nb_prop += 1
now = datetime.datetime.now() + datetime.timedelta(hours = 1)
feedback['content'] = "Nous sommes le " + now.strftime('%d %b %Y à %Hh%Mm%Ss') + "<br />"

if nb_prop > 1 and (now - datetime.datetime.fromtimestamp(time_prop[-1])) < datetime.timedelta(minutes = 2**(len(time_prop)-1)):
    grade = 0
    next_date = datetime.datetime.fromtimestamp(time_prop[-1]) + datetime.timedelta(minutes = 2**(len(time_prop)-1))
    feedback['content'] += "Prochaine proposition autorisée le " + next_date.strftime('%d %b %Y à %Hh%Mm%Ss') + "<br />"
else:
    time_prop.append(now.timestamp())
    if ans['value'] == soluce_num:
        feedback['type'] = "success"
        feedback['content'] += "Bravo, vous avez résolu le challenge."
        grade=100
    else:
        feedback['type'] = "error"
        feedback['content'] += "Ce n'est pas la bonne réponse!"
        if len(time_prop) <= 3:
            if ans['value'] < soluce_num:
                feedback['content'] += "<br />Votre proposition est trop petite."
            else:
                feedback['content'] += "<br />Votre proposition est trop grande."
        grade = 0

==
```

I also use this parameter : 

![Capture d’écran du 2024-02-07 01-04-15](https://github.com/cisstech/platon/assets/6042616/a0b4900e-ba00-4f79-af82-e7e8826cc91b)

The number of tries are infinite but the grader forces to wait 2^{number of tries already done}.

Such behavior seems very good for a public challenge... It avoids users practicing dichotomic search of the result without blocking them.
