### ISSUE TITLE
RadioGroup component not showing properly

### ISSUE THREAD

**Issue by clementga** [cisstech/platon#8]
![image](https://github.com/cisstech/platon/assets/51517972/26989b17-535b-4053-8764-8744f37db8eb)

When using a RadioGroup component and loading an exercise, at first, no text appears, and once you click on at least one option, the text does appear but is then not aligned properly.

**Comment by mciissee** [comment]
Fixed with https://github.com/cisstech/platon/commit/ecc6ff4c27d69575f5e8cb67985665e51888d169 by upgrading @cisstech/nge lib
<img width="1512" alt="Capture d’écran 2023-06-07 à 20 27 09" src="https://github.com/cisstech/platon/assets/30326262/c44b6eb4-fb3a-46c3-b188-c3e1a3f5a0e3">
