### ISSUE TITLE
Automator Editor Issue

### ISSUE THREAD

**Issue by Ofghanirre** [cisstech/platon#9]
Hello ! J'espère que tout va bien ! 
J'ai un problème autour des automates avec le automaton-viewer et automaton-editor. Il semblerait qu'il y ait un problème d'affichage et de gestion des données à travers un exercice platon.

- [x]  L'affichage des options d'automates n'est pas réalisé si la taille de la fenêtre est trop petite, donc dans l'onglet preview de l'éditeur, les options ne s'affichent pas
![image](https://github.com/cisstech/platon/assets/18609818/5e63707f-367b-45e9-9247-558785871d81)

- [x]  L'édition des automates via l'éditeur semble poser problème, en effet les liens ne semblent pas sauvegarder au cours de l'édition et donc il est impossible de comparer correctement deux automates. De plus le fait qu'il y ai 2 syntaxes différentes pour rentrer un automate semble poser problème.  Il faudrait que si on rentre une string, on sort avec un objet ou inverse... Ou alors des fonctions de mapping si possible !

Exemples :
J'ai cet exercice PL:
```ts
input = :wc-automaton-editor
input.debug = true

inputSolution = :wc-automaton-editor

inputSolution.debug = true

builder==
inputSolution.automaton = {
    "states": [
      "S2",
      "S1"
    ],
    "alphabet": [
      "a",
      "b"
    ],
    "position": {
      "S1": {
        "x": 432,
        "y": 199
      },
      "S2": {
        "x": 598,
        "y": 235
      }
    },
    "transitions": [
      {
        "symbols": [
          "a"
        ],
        "toState": "S2",
        "fromState": "S1"
      },
      {
        "symbols": [
          "b"
        ],
        "toState": "S2",
        "fromState": "S2"
      }
    ],
    "initialStates": [
      "S1"
    ],
    "acceptingStates": [
      "S2"
    ]
  }

input.automaton =  {
    "states": [
      "S2",
      "S1"
    ],
    "alphabet": [
      "a",
      "b"
    ],
    "position": {
      "S1": {
        "x": 432,
        "y": 199
      },
      "S2": {
        "x": 598,
        "y": 235
      }
    },
    "transitions": [
      {
        "symbols": [
          "a"
        ],
        "toState": "S2",
        "fromState": "S1"
      },
      {
        "symbols": [
          "b"
        ],
        "toState": "S2",
        "fromState": "S2"
      }
    ],
    "initialStates": [
      "S1"
    ],
    "acceptingStates": [
      "S2"
    ]
  }
==

grader==
grade = 0
feedback = {}
feedback.type = "error"
feedback.content = "Mauvaise réponse"
if (input.automaton === inputSolution.automaton) {
  grade = 100
  feedback.type = "success"
  feedback.content = "Bonne réponse"
}
==


title==
Automaton editor
==

statement ==
Test Implementation
==

form==
{{input}}
==

solution==
{{inputSolution}}
==
```

Et j'obtiens les affichages suivants:
![image](https://github.com/cisstech/platon/assets/18609818/a3950a82-8cbb-4db4-be39-0af565c76f91)

> _On observe que les liens ne sont pas préservés à l'affichage_

Comme on peut le voir dans le code en théorie les 2 champs `automatons`sont identique sur **input** et **inputSolution**, et pourtant :
![image](https://github.com/cisstech/platon/assets/18609818/1e4fb9c7-84a9-4024-af8c-5fc8c22f8144)

Voilà j'espère que c'est assez clair !

**Comment by Ofghanirre** [comment]
Il semblerait qu'il y ai un autre problème, peut être à l'origine de celui ci :

**Comment by mciissee** [comment]
<img width="1512" alt="Capture d’écran 2023-06-07 à 22 08 15" src="https://github.com/cisstech/platon/assets/30326262/61a859b8-d2ba-4682-9e1e-897f241587a2">

**Comment by mciissee** [comment]
Edit : Les variables de la sandbox node sont sauvegardés uniquement si c'est des variables globales (pas de mot clé let/const)
