### ISSUE TITLE
Inline creation of activity or exercices

### ISSUE THREAD

**Issue by plgitlogin** [cisstech/platon#97]
The idea is that you can from a course add an non existing activity -> your are sent to the activity creation senario.
And the same protocol for adding a new exercice to an activity -> a new exercice bouton in the acticvity exercice edition interface.

**Comment by mciissee** [comment]
@plgitlogin This is contrary to the way activities work in a course. To place an activity in a course, the activity must contain courses, and be compiled.

Adding an exercise to an activity at the time of its creation also requires more than simply adding it to an exercise list in the master version, as the activity has groups.

To sum up, the methodology used is to create a resource, test it to make sure it works, change its status to `ready` and then add it to a course if it's an activity, or to an activity if it's an exercise.
